environment:
  NODEJS_VERSION: "16"
  PREBUILD_UPLOAD:
    secure: oNyyLE7/Oq3TUGZPz6DkLFPUuQzc8FiFS1iuPp7LZ2fyOP/UF4Np4NzJmWcXVyY/

platform:
  - x64
  - x86

image: Ubuntu

stack: node 16, python 3.10

install:
  - git submodule update --init --recursive
  - npm install

build: off

test_script:
  - npm test

branches:
  only:
    - master
    - /^v.*$/

deploy_script: IF "%APPVEYOR_REPO_TAG%" == "true" (npm run prebuild && npm run prebuild:upload -u %PREBUILD_UPLOAD%)
