name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - released

jobs:

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 14
          - 16
          - 18
      fail-fast: false
    name: Testing Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Update node-gyp for Node 14
        if: ${{ matrix.os == 'windows-latest' && matrix.node == '14' }}
        run: |
          $WhereNode = Get-Command node | Select-Object -ExpandProperty Definition
          $NodeDirPath = Split-Path $WhereNode -Parent
          $NodeModulesPath = $NodeDirPath + "\node_modules\npm\node_modules\npm-lifecycle"
          cd $NodeModulesPath
          npm install node-gyp@9.x
      - name: Update node-gyp for Node 16 or 18
        if: ${{ matrix.os == 'windows-latest' && ( matrix.node == '16' || matrix.node == '18' ) }}
        shell: powershell
        run: |
          npm install --global node-gyp@latest

      - run: npm install
      - run: npm test

  prebuild-test:
    strategy:
      matrix:
        os_and_node:
          # - { os: "ubuntu-latest", node: "18" }
          # - { os: "macos-latest", node: "18" }
          - { os: "windows-latest", node: "18" }
      fail-fast: false
    name: Prebuild on ${{ matrix.os_and_node.os }}
    runs-on: ${{ matrix.os_and_node.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.os_and_node.node }}
      - run: npm install --ignore-scripts
      - run: npx --no-install prebuild -r node -t 14.0.0 -t 16.0.0 -t 18.0.0 -t 20.0.0
      - run: npx --no-install prebuild -r electron -t 22.0.0 -t 23.0.0 -t 24.0.0
      - if: matrix.os_and_node.os == 'macos-latest'
        run:
          npx --no-install prebuild -r node -t 14.0.0 -t 16.0.0 -t 18.0.0 -t 20.0.0 --arch arm64
          npx --no-install prebuild -r electron -t 22.0.0 -t 23.0.0 -t 24.0.0 --arch arm64

  publish:
    if: ${{ github.event_name == 'release' }}
    name: Publishing to NPM
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  prebuild:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    name: Prebuild on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: publish
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --ignore-scripts
      - run: npx --no-install prebuild -r node -t 10.0.0 -t 12.0.0 -t 14.0.0 -t 16.0.0 -t 18.0.0 -t 20.0.0 -u ${{ secrets.GH_TOKEN }}
      # Prebuilding for Electron 13+ on Windows fails with
      #   win_delay_load_hook.cc
      # conversions.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class v8::Local<class v8::ArrayBuffer> __cdecl v8::ArrayBuffer::New(class v8::Isolate *,class std::shared_ptr<class v8::BackingStore>)" (__imp_?New@ArrayBuffer@v8@@SA?AV?$Local@VArrayBuffer@v8@@@2@PEAVIsolate@2@V?$shared_ptr@VBackingStore@v8@@@std@@@Z) referenced in function "void __cdecl node_tree_sitter::InitConversions(class v8::Local<class v8::Object>)" (?InitConversions@node_tree_sitter@@YAXV?$Local@VObject@v8@@@v8@@@Z) [D:\a\node-tree-sitter\node-tree-sitter\build\tree_sitter_runtime_binding.vcxproj]
      - if: matrix.os != 'windows-latest'
        run: npx --no-install prebuild -r electron -t 21.0.0 -t 22.0.0 -t 23.0.0 -u ${{ secrets.GH_TOKEN }}
      # - if: matrix.os == 'windows-latest'
      #   run: npx --no-install prebuild -r electron -t 21.0.0 -t 22.0.0 -t 23.0.0 --arch ia32 -u ${{ secrets.GH_TOKEN }}
      - if: matrix.os == 'macos-latest'
        run: npx --no-install prebuild -r electron -t 21.0.0 -t 22.0.0 -t 23.0.0 --arch arm64 -u ${{ secrets.GH_TOKEN }}
